import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Header from "./_components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={inter.className + ' overflow-x-hidden flex flex-col px-2 py-4 justify-center items-center gap-6 relative w-full  lg:flex-row lg:items-start lg:justify-end bg-primary text-white'}>
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
